// <auto-generated />
namespace genetrix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _600 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_600));
        
        string IMigrationMetadata.Id
        {
            get { return "202211221128485_600"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
