// <auto-generated />
namespace genetrix.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _34 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_34));
        
        string IMigrationMetadata.Id
        {
            get { return "202210210009057_34"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
